// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQ-Yy-7VbS-Jy1sXAgMjtHqwUKNHPz-0',
    appId: '1:127161800012:web:f19743e55ae653638f2be9',
    messagingSenderId: '127161800012',
    projectId: 'fir-bloc-login-32115',
    authDomain: 'fir-bloc-login-32115.firebaseapp.com',
    storageBucket: 'fir-bloc-login-32115.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcYgXFWJEiuEn0vR0OUaczCKM1tVgPe-Q',
    appId: '1:127161800012:android:42dbe60f784f6f4d8f2be9',
    messagingSenderId: '127161800012',
    projectId: 'fir-bloc-login-32115',
    storageBucket: 'fir-bloc-login-32115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPXe2ul4xQUzEJsHNaznsRJnL0U1wRII',
    appId: '1:127161800012:ios:e395c178a50dcfd48f2be9',
    messagingSenderId: '127161800012',
    projectId: 'fir-bloc-login-32115',
    storageBucket: 'fir-bloc-login-32115.appspot.com',
    iosBundleId: 'com.example.demoBlocGmaillogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuPXe2ul4xQUzEJsHNaznsRJnL0U1wRII',
    appId: '1:127161800012:ios:e395c178a50dcfd48f2be9',
    messagingSenderId: '127161800012',
    projectId: 'fir-bloc-login-32115',
    storageBucket: 'fir-bloc-login-32115.appspot.com',
    iosBundleId: 'com.example.demoBlocGmaillogin',
  );
}
